/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pCxiNI4CkTq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"

export function Detector() {
  return (
    (<div className="container mx-auto py-8 px-4 sm:px-6 lg:px-8">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h1 className="text-2xl font-bold mb-4">Deepfake Analysis</h1>
          <Card>
            <CardHeader>
              <CardTitle>Uploaded Video</CardTitle>
            </CardHeader>
            <CardContent>
              <video className="w-full h-auto rounded-lg" controls>
                <source src="/placeholder.mp4" type="video/mp4" />
              </video>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button>Download Report</Button>
            </CardFooter>
          </Card>
        </div>
        <div>
          <Card>
            <CardHeader>
              <CardTitle>Deepfake Likelihood</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div className="text-4xl font-bold">87%</div>
                <div className="text-muted-foreground">Likely Deepfake</div>
              </div>
              <Progress value={87} aria-label="Deepfake likelihood" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Detected Manipulations</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                <li>
                  <div className="flex items-center justify-between">
                    <div>Facial Inconsistencies</div>
                    <div className="text-muted-foreground">High Confidence</div>
                  </div>
                  <Progress value={90} aria-label="Facial Inconsistencies confidence" />
                </li>
                <li>
                  <div className="flex items-center justify-between">
                    <div>Lighting and Shadows</div>
                    <div className="text-muted-foreground">Medium Confidence</div>
                  </div>
                  <Progress value={65} aria-label="Lighting and Shadows confidence" />
                </li>
                <li>
                  <div className="flex items-center justify-between">
                    <div>Eye and Lip Movement</div>
                    <div className="text-muted-foreground">High Confidence</div>
                  </div>
                  <Progress value={85} aria-label="Eye and Lip Movement confidence" />
                </li>
                <li>
                  <div className="flex items-center justify-between">
                    <div>Texture and Skin</div>
                    <div className="text-muted-foreground">High Confidence</div>
                  </div>
                  <Progress value={92} aria-label="Texture and Skin confidence" />
                </li>
                <li>
                  <div className="flex items-center justify-between">
                    <div>Head Movement and Pose</div>
                    <div className="text-muted-foreground">Medium Confidence</div>
                  </div>
                  <Progress value={75} aria-label="Head Movement and Pose confidence" />
                </li>
              </ul>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Overall Confidence</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div className="text-4xl font-bold">92%</div>
                <div className="text-muted-foreground">High Confidence</div>
              </div>
              <Progress value={92} aria-label="Overall confidence" />
            </CardContent>
          </Card>
        </div>
      </div>
    </div>)
  );
}
